# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170802_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='District',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Hospital_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='State',
            field=models.TextField(),
        ),
    ]
