# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170802_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Address',
            field=models.CharField(max_length=310),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='District',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Hospital_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='State',
            field=models.CharField(max_length=50),
        ),
    ]
