# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170803_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Address',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Contact',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='District',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Hospital_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbankdata',
            name='State',
            field=models.CharField(max_length=50),
        ),
    ]
