# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170803_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankdata',
            name='Hospital_name',
            field=models.TextField(),
        ),
    ]
